### PR TITLE
initial commit to support custom elk template

### PR DESCRIPTION
**Pull request by ridakk**
here is my initial implemenation to have custom templates just for your inspection.

### CODE REVIEW

**Comment by sv2** [comment]
Thanks a lot ! I'd like to think a bit more about this one - here are some considerations ...

Ideally, I'd like to avoid extending ES schema with specifically defined custom attributes - i.e. second "subschema" merged with default one 
It would not be easy to use - would need to create and maintain custom definition, make sure it's updated when application needs change. Also may lead to indexing errors: if custom schema defined some attribute as integer, but then app developer by some reason  added it as string, indexing will fail. 

I'm thinking instead to define flexible custom attributes in the schema by using dynamic mapping, like that: 

```json
{
   "attributes": {
       "path_match": "attributes.*",
           "mapping": {
              "type": "keyword"
             }
         }
}
```

This should allow app to add anything under `rrr.attributes` and ES would index it correctly as long as values casted to strings. Similar to how, for example, http request headers are processed with current schema - there could be any name of header. 
I'll think a bit more whether to have typed custom attributes - i.e. something like "attributes.int.*" - could be useful  for aggregations

**Comment by ridakk** [comment]
makes sense. so there won't be any need to have a way to let app use its own schema.

**Comment by ridakk** [comment]
closing this pull request

**Comment by sv2** [comment]
I've open #28 to track this - per our discussions

**Pull request closed without merging**
